name: pwgen
description: Generate strong, memorable passwords from your CLI.
version: 1.0.0

environment:
  sdk: ">=2.14.4 <3.0.0"

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^1.0.0
  test: ^1.20.1
dependencies:
  args: ^2.3.0
  cli_util: ^0.3.5
  english_words: ^4.0.0
